num1 = int(input("enter the num1\n"))
num2 = int(input("enter the num2\n"))
sum = (num1+num2)
subst = (num1-num2)
pow = (num1**num2)
mul = (num1*num2)
div = (num1/num2)
max = max (num1, num2)
min = min (num1, num2)
print(f"The sum of {num1} and {num2} is {sum}")
print(f"The subst of {num1} and {num2} is {subst}")
print(f"The pow of {num1} and {num2} is {pow}")
print(f"The mul of {num1} and {num2} is {mul}")
print(f"The div of {num1} and {num2} is {div}")
print(f"The max of {num1} and {num2} is {max}")
print(f"The min of {num1} and {num2} is {min}")
